"""ReID session helper for the continuous video pipeline.

The main video loop now runs continuously and batches captures on a worker thread.
This module keeps ReID state (gallery + primary person-of-interest) across those
batches, while preserving the same `reid_report.json` schema generated by
`generate_reid_report()`.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Optional

from src_video.services.person_reid_service.integration import (
    generate_reid_report,
    run_person_reid_on_detections,
)
from src_video.services.person_reid_service.tracker import PersonReIDEngine


@dataclass
class ReIDSession:
    """Stateful wrapper around `PersonReIDEngine` for continuous capture."""

    reid_engine: PersonReIDEngine
    detection_output_dir: Path
    report_path: Path
    saved_images_dir: Optional[Path] = None
    primary_person_id: Optional[str] = None

    def process_image(self, image_stem: str) -> Dict[str, Any]:
        """Update ReID state for a newly processed image.

        Assumes detection has already produced crops under:
            detection_output_dir/crops/<image_stem>/
        """

        crops_root = self.detection_output_dir / "crops"

        # First valid capture becomes the person-of-interest reference.
        if not self.primary_person_id:
            reg = run_person_reid_on_detections(
                crops_root=crops_root,
                image_id=image_stem,
                reid_engine=self.reid_engine,
                is_gallery_registration=True,
            )
            if reg.get("success") and reg.get("person_id"):
                self.primary_person_id = str(reg["person_id"])
                print(f"[reid] Person of interest set: {self.primary_person_id}")
            else:
                print(f"[reid] Registration skipped (no detections) for {image_stem}")

            self._write_report()
            return {
                "success": bool(reg.get("success")),
                "mode": "register",
                "primary_person_id": self.primary_person_id,
                "result": reg,
            }

        # Subsequent captures: re-id against gallery.
        res = run_person_reid_on_detections(
            crops_root=crops_root,
            image_id=image_stem,
            reid_engine=self.reid_engine,
            is_gallery_registration=False,
        )

        present = False
        detected_person_ids: set[str] = set()
        if res.get("success"):
            summary = res.get("summary") or {}
            identified_by_part = summary.get("identified_by_part") or {}
            for pid in identified_by_part.values():
                if pid:
                    detected_person_ids.add(str(pid))
            present = self.primary_person_id in detected_person_ids

        if present:
            print(f"[reid] Re-identified person of interest: {self.primary_person_id}")
        else:
            print(f"[reid] Couldn't re-identify person: {self.primary_person_id}")

        if detected_person_ids:
            print(f"[reid] Detected person IDs: {sorted(detected_person_ids)}")
        else:
            print("[reid] Detected person IDs: []")

        self._write_report()

        return {
            "success": bool(res.get("success")),
            "mode": "reid",
            "primary_person_id": self.primary_person_id,
            "primary_person_present": present,
            "detected_person_ids": sorted(detected_person_ids),
            "result": res,
        }

    def _write_report(self) -> None:
        self.report_path.parent.mkdir(parents=True, exist_ok=True)
        generate_reid_report(
            reid_engine=self.reid_engine,
            output_path=self.report_path,
            saved_images_dir=self.saved_images_dir,
            primary_person_id=self.primary_person_id,
        )
