#!C:\Users\karad\OneDrive - University of Calgary\Desktop\Capstone\capstone-audio-to-text\whisperX\venv311\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
